# Generated by Django 2.1.7 on 2019-03-21 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_food', '0002_auto_20190320_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_categories', models.CharField(choices=[(1, 'Первые блюда'), (2, 'Вторые блюда'), (3, 'Напитки'), (4, 'Десерты'), (5, 'Алкоголь')], max_length=100)),
                ('departments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mealcategories', to='crm_food.Department')),
            ],
        ),
        migrations.AlterField(
            model_name='status',
            name='name_of_statuses',
            field=models.CharField(choices=[(1, 'Pending'), (2, 'Done')], default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='table',
            name='name_of_tables',
            field=models.CharField(max_length=255),
        ),
    ]
