# Generated by Django 2.1.7 on 2019-03-21 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_food', '0003_auto_20190321_1953'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MealCategories',
            new_name='MealCategory',
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='crm_food.MealCategory'),
        ),
    ]
