# Generated by Django 2.1.7 on 2019-03-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_food', '0004_auto_20190321_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealcategory',
            name='name_of_categories',
            field=models.PositiveIntegerField(choices=[(1, 'Первые блюда'), (2, 'Вторые блюда'), (3, 'Напитки'), (4, 'Десерты'), (5, 'Алкоголь')], default=1),
        ),
        migrations.AlterField(
            model_name='status',
            name='name_of_statuses',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Done')], default=1, max_length=255),
        ),
    ]
