# Generated by Django 2.1.7 on 2019-03-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_food', '0005_auto_20190321_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='meal',
        ),
        migrations.AddField(
            model_name='order',
            name='meals',
            field=models.ManyToManyField(blank=True, related_name='orders', to='crm_food.Meal'),
        ),
    ]
