# Generated by Django 2.1.7 on 2019-03-22 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_food', '0006_auto_20190321_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_check', models.DateTimeField(auto_now_add=True)),
                ('service_fee', models.PositiveSmallIntegerField(default=1)),
                ('total_sum', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='meals',
        ),
        migrations.AddField(
            model_name='meal',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='meals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_item', to='crm_food.Meal'),
        ),
        migrations.AddField(
            model_name='checks',
            name='orders',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm_food.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm_food.OrderItem'),
        ),
    ]
