# Generated by Django 2.1.7 on 2019-03-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_food', '0007_auto_20190322_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='meals',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='meals',
            field=models.ManyToManyField(related_name='ordersitem', to='crm_food.Meal'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name_of_statuses',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Done')], default=1),
        ),
    ]
